python train.py --model_name_or_path 'models/lucy-base' \
  --do_train \
  --num_train_epochs 1 \
  --source_lang 'ja' \
  --target_lang 'en' \
  --dataset_name 'dataset/load.py' \
  --output_dir 'train/lucy-base/' \
  --logging_steps 50 \
  --save_strategy 'epoch' \
  --overwrite_output_dir True \
  --use_fast_tokenizer False \
  --preprocessing_num_workers 8 \
  --dataloader_num_workers 8 \
  --tf32 True \
  --bf16 True \
  --overwrite_output_dir \
  --per_device_train_batch_size=8 \
  --max_source_length=128 \
  --max_target_length=128