python train.py --model_name_or_path 'models/lucy-base' \
  --do_train \
  --num_train_epochs 15 \
  --source_lang 'ja' \
  --target_lang 'en' \
  --dataset_path 'dataset/data/train/datasets/checkpoint1' \
  --output_dir 'train/lucy-base/checkpoint15/' \
  --logging_steps 50 \
  --save_strategy 'epoch' \
  --overwrite_output_dir True \
  --use_fast_tokenizer False \
  --preprocessing_num_workers 8 \
  --dataloader_num_workers 8 \
  --overwrite_output_dir \
  --per_device_train_batch_size=32 \
  --per_device_eval_batch_size=32 \
  --max_source_length=100 \
  --max_target_length=100 \
  --learning_rate 1e-3